/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javachatudp;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Nguyen Hai Dang
 */
public class ChatBoxFrame extends javax.swing.JFrame {

    private String chatName;
    private String idRoom;
    private String id;
    private DatagramSocket connectSocket;
    private DatagramPacket sendPacket;
    private DefaultListModel contentListModel;

    /**
     * Creates new form ChatBoxFrame
     */
    public ChatBoxFrame() {
        initComponents();
    }

    public ChatBoxFrame(DatagramSocket socket, DatagramPacket packet, String id, String name, String idRoom) throws SocketException {
        initComponents();
        this.chatName = name;
        this.idRoom = idRoom;
        this.id = id;
        this.sendPacket = packet;
        this.connectSocket = socket;

        roomNameLabel.setText("Phòng chat " + this.idRoom);
        nickNameLabel.setText("Tên chat: " + this.chatName);
        idLabel.setText("#" + this.id);
        contentListModel = new DefaultListModel();
        chatContentList.setModel(contentListModel);
        chatContentList.setCellRenderer(new MyListCellRenderer(this.chatName));

        Thread readThread = new Thread(() -> {
            try {
                while (true) {
                    byte[] buff = new byte[1024];
                    DatagramPacket din = new DatagramPacket(buff, buff.length);
                    connectSocket.receive(din);
                    String recvMessage = new String(din.getData()).trim();
                    contentListModel.addElement(recvMessage);
                }
            } catch (Exception ex) {
                System.out.println("Receive error: " + ex);
            }
        });
        readThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatContentList = new javax.swing.JList<>();
        exitButton = new javax.swing.JButton();
        roomNameLabel = new javax.swing.JLabel();
        nickNameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageTextArea.setColumns(20);
        messageTextArea.setLineWrap(true);
        messageTextArea.setRows(1);
        jScrollPane1.setViewportView(messageTextArea);

        sendButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sendButton.setText("Gửi");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        chatContentList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(chatContentList);

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exitButton.setText("Thoát");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        roomNameLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        roomNameLabel.setForeground(new java.awt.Color(255, 0, 0));
        roomNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roomNameLabel.setText("Phòng chat");

        nickNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nickNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nickNameLabel.setText("Tên chat:");

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLabel.setText("#");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(roomNameLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(nickNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(idLabel)))
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomNameLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nickNameLabel)
                            .addComponent(idLabel)))
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String message = messageTextArea.getText();

        if (message.isEmpty()) {
            return;
        }

        messageTextArea.setText("");
        try {
            contentListModel.addElement(message);
            sendPacket.setData((this.chatName + ": " + message).getBytes());
            connectSocket.send(sendPacket);
        } catch (Exception ex) {
            System.out.println("Send error: " + ex);
        }

    }//GEN-LAST:event_sendButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        try {
            sendPacket.setData(("/ext-" + this.chatName).getBytes());
            connectSocket.send(sendPacket);
        } catch (Exception ex) {
            System.out.println("Exit error: " + ex);;
        }
        connectSocket.close();
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> chatContentList;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JLabel nickNameLabel;
    private javax.swing.JLabel roomNameLabel;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
